/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hrlqzpikvkmwbhvofhgc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybHF6cGlrdmttd2Jodm9maGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjcyNzEsImV4cCI6MjA3Mjc0MzI3MX0.eEJVLV_E-TV7bD3J89HsSijZ567nFeiEvlbGSM-QRwk"